SalesNet v1.3/trunk/SalesNet.WebUI/Controllers/CustomerController.cs
using System;
using System.Web.Mvc;
using Ap21API.Entities.Customer;
using SalesNet.WebUI.Classes;
using SalesNet.WebUI.Infrastructure;
using System.Linq;
namespace SalesNet.WebUI.Controllers
{
    [NoCache]
    [EnhancedAuthorizedAttribute]
    public class CustomerController : BaseController
    {
        private readonly IAppSessionWrapper session;
        private Customer customer;
        private CustomerCreditStatus creditStatus;

        public CustomerController(IAppSessionWrapper sessionWrapper)
        {
            this.session = sessionWrapper;
        }

        public ActionResult Index()
        {
            var customers = Customers.Find(startRow: 1, pageRows: 9999);

            if (customers.Count > 0)
            {
                if (!session.Current.IsAgent)
                {
                    customer = customers[0];
                    session.Current.CustomerId = customer.Id;
                    session.Current.CustomerName = customer.Name;
                    session.Current.IsAgent = false;
                    creditStatus = new CustomerCreditStatus(customer);

                    if(!creditStatus.IsNormal)
                    {
                        if (!creditStatus.CanContinue)
                        {
                            if (TempData["PreviousController"] != null && TempData["PreviousController"].ToString() == "Session")
                            {
                                FlashError("Login unsuccessful: Account on permanent suspend","Login");
                                return RedirectToRoute(new { controller = "Session", action = "LogIn" });
                            }
                        }
                        
                        AlertCreditStatus();    
                    }

                    return RedirectToRoute(new {controller = "Home", action = "Index"});
                }
                else
                {
                    return View(customers);
                }
            }
            else
            {
                return RedirectToRoute(new { controller = "Error", action = "Index", errormsg = "No Customer set up in AP21 system", errorcode = "5046" });
            }
        }

        private void AlertCreditStatus()
        {
            
            FlashWarning(description: creditStatus.Message());
            //if (creditStatus.CanContinue)
            //{
            //    FlashNotice(description: creditStatus.Message());
            //}
            //else
            //{
            //    FlashWarning(description: creditStatus.Message());
            //}
        }

        [HttpGet]
        public PartialViewResult CustomerList(Customers customers)
        {
            if (customers == null)
                customers = Customers.Find(startRow: 1, pageRows: 9999);

            return PartialView(customers);
        }

        [HttpGet]
        public JsonResult SearchCustomerList(string searchtext)
        {
            
            var  customers = Customers.Find(startRow: 1, pageRows: 9999).Customer.Where(x=>x.Name.ToLower().Contains(searchtext.ToLower()));
            return Json(customers,JsonRequestBehavior.AllowGet);
        }

        public PartialViewResult RenderCustomerList()
        {
            var customers = Customers.Find(startRow: 1, pageRows: 9999);
            ViewBag.CustomerId = session.Current.CustomerId;
            
            return PartialView("CustomerList", customers);
            
        }

        public ActionResult RedirectToHome(FormCollection fc)
        {
            session.Current.CustomerId = fc.Get("selectedCustomer");

            if(!String.IsNullOrEmpty(session.Current.CustomerId))
            {
                customer = Customer.Find(id: session.Current.CustomerId);
                session.Current.CustomerName = customer.Name;
                session.Current.IsAgent = true;

                creditStatus = new CustomerCreditStatus(customer);

                if (!creditStatus.IsNormal)
                {
                    AlertCreditStatus();
                }

                return RedirectToRoute(new { controller = "Home", action = "Index" });
            }
            else
            {
                FlashNotice("Please select a customer");
                return RedirectToAction("Index");
            }           
        }

        public ActionResult SelectCustomer(string id)
        {
            session.Current.CustomerId = id;

            if (!String.IsNullOrEmpty(session.Current.CustomerId))
            {
                customer = Customer.Find(id: session.Current.CustomerId);
                session.Current.CustomerName = customer.Name;
               // session.Current.IsAgent = true;

                creditStatus = new CustomerCreditStatus(customer);
                //added by raju for regarding #120 to prevent suspended accounts from login on 9 feb 2013 
                if (!session.Current.IsAgent)
                {
                    if (customer.CreditStatusFlag == 1)
                    {
                        if (TempData["PreviousController"] != null && TempData["PreviousController"].ToString() == "Session")
                        {
                            FlashError("Login unsuccessful: Account on permanent suspend", "Login");

                            return RedirectToRoute(new { controller = "Session", action = "LogIn" });
                        }
                    }
                }
                //end
                else if (!creditStatus.IsNormal)
                {
                    AlertCreditStatus();
                }

                var landingpage = System.Configuration.ConfigurationManager.AppSettings["LandingPage"];
                if (landingpage != null && landingpage == "*Products*")
                    return RedirectToRoute(new { controller = "Products", action = "Index" });

                return RedirectToAction("Index", "Order");

                //var customers = Customers.Find(startRow: 1, pageRows: 9999);
                //if (customers.Count == 1)
                //{
                //    ViewBag.CustomerId = customers[0].Id;
                //    return RedirectToAction("SelectCustomer", "Customer", new { id = ViewBag.CustomerId });

                //}

                //return RedirectToRoute(new { controller = "Home", action = "Index" });
            }
            else
            {
                FlashNotice("Please select a customer");
                return RedirectToAction("Index");
            }   
        }

        [HttpGet]
        public JsonResult Locations()
        {
            var customer = Customer.Find(session.Current.CustomerId);
            var locations = customer.Locations;

            return Json(locations, JsonRequestBehavior.AllowGet);
        }
    }
}

SalesNet v1.3/trunk/SalesNet.WebUI/Controllers/OrderController.cs
using System;
using System.Web.Mvc;
using Ap21API.Entities.Customer;
using Ap21API.Entities.Order;
using SalesNet.Domain.Entities;
using SalesNet.WebUI.DataSetGenerators;
using SalesNet.WebUI.Infrastructure;
using SalesNet.WebUI.Models;
using SalesNet.WebUI.Helpers;
using SalesNet.WebUI.Classes;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using Order = Ap21API.Entities.Order.Order;


namespace SalesNet.WebUI.Controllers
{  
    [NoCache]
    [EnhancedAuthorizedAttribute]
    public partial class OrderController : BaseController
    {
        private CustomerCreditStatus creditStatus;
        private readonly IAppSessionWrapper session;

        public OrderController(IAppSessionWrapper appSessionWrapper)
        {
            session = appSessionWrapper;
        }

        

        public ViewResult Index()
        {
            ViewBag.CustomerId = session.Current.CustomerId;
            TempData["ActivePage"] = "Order History";
            

            return View();
        }

        [ValidateInput(false)]
        public PartialViewResult HistoryIndex(string trans_num = null, string ref_num = null, string created_date_from = null,
            string created_date_to = null, string product_code_desc = null, string order_type = null)
        {
            var searchCriteria = new OrderSearchViewModel(trans_num, ref_num, created_date_from,
            created_date_to, product_code_desc, order_type);
            return PartialView(searchCriteria);
        }

        [ValidateInput(false)]
        public PartialViewResult HistoryItem(string trans_num = null, string ref_num = null, string created_date_from = null,
            string created_date_to = null, string product_code_desc = null, string order_type = "Orders", int page = 1)
        {
            
            const int pageRow = 20;
            int startRow = (page - 1) * pageRow + 1;	

            try
            {
                ValidateSearchCriteria(ref trans_num, ref ref_num, ref created_date_from, ref created_date_to, ref product_code_desc, ref order_type);
            }
            catch (System.FormatException)
            {
                return PartialView();
            }

            var searchCriteria = new OrderSearchViewModel(trans_num, ref_num, created_date_from, 
                created_date_to,product_code_desc, order_type);

            var orderRepository = Orders.Find(createdDateFrom: created_date_from, createdDateTo: created_date_to, customerReference: ref_num, pageRows: pageRow,
                                                 productFilter: product_code_desc, startRow: startRow,
                                                 transactionNumber: trans_num, transactionType: order_type);


            if (orderRepository!=null && orderRepository.Order.Count>0)
            {
                int PageCurrent = (int)Math.Ceiling((decimal)orderRepository.PageStartRow / pageRow);
                var viewModel = orderRepository.Order.ToPagedList(PageCurrent - 1, pageRow,
                                                                  orderRepository.TotalRows, searchCriteria.ToDictionary());
                return PartialView(viewModel); 
            }
            else
            {
                return PartialView();
            }
        }

        private void ValidateSearchCriteria(ref string trans_num, ref string ref_num, ref string created_date_from,
            ref string created_date_to, ref string product_code_desc, ref string order_type)
        {            
            if (trans_num == "" || trans_num == "Trans.#")
            {
                trans_num = null;
            }

            if (ref_num == "" || ref_num == "Ref #")
            {
                ref_num = null;
            }

            if (created_date_from == "" || created_date_from == "Created From")
            {
                created_date_from = null;
            }

            if (created_date_to == "" || created_date_to == "Created To")
            {
                created_date_to = null;
            }

            if (product_code_desc == "" || product_code_desc == "Product Code/Desc")
            {
                product_code_desc = null;
            }

            if (order_type == "")
            {
                order_type = null;
            }

            if (trans_num != null)
            {
                Regex regex = new Regex(@"^[0-9]+$");
                bool b = regex.IsMatch(trans_num);
                if (!b)
                    throw new System.FormatException();
            }

            if (created_date_from != null)
            {
                created_date_from = String.Format("{0:yyyy-MM-dd}", Convert.ToDateTime(created_date_from));
            }

            if (created_date_to != null)
            {
                created_date_to = String.Format("{0:yyyy-MM-dd}", Convert.ToDateTime(created_date_to));
            }
        }

        public PartialViewResult CurrentOrders()
        {
			PutCurrentOrderInViewBag();
			return PartialView();
        }

        [HttpPost]
        public ActionResult CurrentOrders(CurrentOrderViewModel model)
        {
            return RedirectToAction("Index", "Home");
        }

		public PartialViewResult CurrentOrdersDetail()
		{
			PutCurrentOrderInViewBag();
			return PartialView();
		}

        [HttpGet]
        public ActionResult DeleteOrders()
        {
            try
            {
                Domain.Entities.Order.DeleteCurrentOrder();
            }
            catch (Exception e)
            {
                FlashError(e.Message);
            }

			PutCurrentOrderInViewBag();
            return PartialView("CurrentOrders");
        }

        [HttpGet]
        public void DeleteOrdersFromFinalisePage()
        {
            try
            {
                Domain.Entities.Order.DeleteCurrentOrder();
            }
            catch (Exception e)
            {
                FlashError(e.Message);
            }
        }

        [HttpGet]
        public ActionResult RemoveOrder(string orderDetailId)
        {
            var model = new MessageModel();

            try
            {
                Domain.Entities.Order.DeleteCurrentSingleOrder(orderDetailId);
                model.MessageCode = 3;
            }
            catch (Exception e)
            {
                model.Error = e.Message;
            }

			PutCurrentOrderInViewBag();
            return PartialView("CurrentOrders", model);
        }

        [HttpGet]
        public void RemoveOrderFromFinalisePage(string orderDetailId)
        {
            var model = new FinaliseOrderViewModel();

            try
            {
                Domain.Entities.Order.DeleteCurrentSingleOrder(orderDetailId);
                model.MessageModel.MessageCode = 3;
            }
            catch (Exception e)
            {
                model.MessageModel.Error = e.Message;
            }
        }


        private void AlertCreditStatus()
        {
            // used to disable/enable the submit link
            TempData["EnableSubmit"] = creditStatus.CanContinue;

            if(creditStatus.CanContinue)
            {
                FlashWarning(description: creditStatus.Message()); 
            }else
            {
                FlashError(description: creditStatus.Message());
            }    
        }

        [ValidateInput(false)]
        public ActionResult savedelivery(string id, string customerReference, string deliveryInstructions, string specialInstructions)
        {
            try
            {

                Domain.Entities.Order.SaveDeliveryDetails(customerReference, deliveryInstructions, specialInstructions);
                
              //FlashNotice("Delivery Details Saved successfully");                
                //return RedirectToAction("FinaliseOrder");
              return RedirectToAction("Index", "Product");
            }
            catch (Exception e)
            {
                FlashError(e.Message);

                return RedirectToAction("FinaliseOrder");
            }
        }
        
        [ValidateInput(false)]
        
        public ActionResult SendOrder(string id, string customerReference, string deliveryInstructions, string specialInstructions)
        {
            try
            {
                Domain.Entities.Order.FinaliseCurrentOrder(customerReference, deliveryInstructions, specialInstructions);
                
                FlashNotice("Order has been sent to process successfully");

                return RedirectToAction("OrderDetails", new { id = id });
               
            }
            catch (Exception e)
            {
                FlashError(e.Message);

                return RedirectToAction("FinaliseOrder");
            }         
        }
        

        [HttpPut]
        public void ChangeDeliveryAddress(string id)
        {
            Domain.Entities.Order.ChangeDeliveryAddress(id);
        }

        [HttpGet]
        public ActionResult ChangeDeliveryAddress1(string id)
        {
            Domain.Entities.Order.ChangeDeliveryAddress(id);
            return RedirectToAction("FinaliseOrder");
        }
        [HttpGet]
        public ActionResult FinaliseOrder()
        {
            var model = Domain.Entities.Order.CurrentOrder ?? new Order();
            var customer = Customer.Find(AppSession.CurrentSession.CustomerId);
            creditStatus = new CustomerCreditStatus(customer);
            if (customer != null)
            {
                ViewBag.Locations = customer.Locations.Location;
            }
            if(!creditStatus.IsNormal)
            {
                AlertCreditStatus();
            }
            TempData["ActivePage"] = "ViewCart";
            return View(model); 
        }

        public PartialViewResult FinaliseOrderDetail()
        {
            TempData["customerReference"] = TempData["customerReference"] ?? String.Empty;

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/Dashboard.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_HtmlHead")
</head>

    <body class="dashboard" style="text-align: left;">
    <center>
    <div style="width:1000px; text-align:left;">
        @Html.Partial("_Header")
        @Html.Partial("_Navigation_site")

        <div id="promo_banner">
            <div class="shadow top"></div>
            <div class="shadow bottom"></div>
            @Html.PromoBanner("~/Content/images/content/promo_banner.jpg")
        </div>


		<div id="container">
            
                @RenderSection("Sidebar")
            
            
		    <div id="content" >
			    @RenderBody()
			</div>
           @* @RenderSection("Order_Sidebar")*@
		</div>

		@Html.Partial("_Footer")
        </div>
        </center>
	</body>
</html>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/EmptyLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_HtmlHead")
</head>

<body class="application">


    <center><div style="width:1000px; text-align:left;">
        @Html.Partial("_EmptyHeader")
        

		<div id="container">

			<div id="content">
			    @RenderBody()
			</div>
         
		</div>

		@Html.Partial("_Footer")
          </div>
        </center>
      
	</body>
</html>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_HtmlHead")
</head>

<body class="application">

    <center><div style="width:1000px; text-align:left;">
        @Html.Partial("_Header")
        @Html.Partial("_Navigation_site")

		<div id="container">
             @RenderSection("Sidebar",false)
             @RenderSection("FreetextSearch", false)
			<div id="content" style ="width:100%">
			    @RenderBody()
			</div>
          @RenderSection("Order_Sidebar", false)
		</div>

		@Html.Partial("_Footer")
        </div>
        </center>
	</body>
    
       
</html>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/ProductLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    @Html.Partial("_HtmlHead")
</head>

<body class="application">
    <center><div style="width:1000px; text-align:left;">
        @Html.Partial("_Header")
        @Html.Partial("_Navigation_site")

		<div id="container">
             @RenderSection("Sidebar",false)
             @RenderSection("FreetextSearch", false)
			<div id="content" style ="width:80%">
			    @RenderBody()
			</div>
          @RenderSection("Order_Sidebar", false)
		</div>

		@Html.Partial("_Footer")
        </div>
        </center>
	</body>
</html>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/SessionLayout.cshtml
<!DOCTYPE html>
<html>
  <head>
    @Html.Partial("_HtmlHead")
  </head>

  <body class="session">
    <center><div style="width:1000px; text-align:left;">
      <div id="container">
        @Html.Partial("_Header")
        <div id="content">
            @RenderBody()
        </div>
        
		@Html.Partial("_Footer")
      </div>
       </div>
        </center>
  </body>
  
</html>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/_AccountDetails.cshtml
@using Ap21API.Entities.Customer
@using SalesNet.WebUI.Classes;
@Html.JavaScript("new Account();")
<div id="account_info" class="account_details">
<style>

.ui-widget-header
{
background-color: white; 
border-top-style: none; 
border-right-style: none;
 border-bottom-style: none;
 border-left-style: none;
 display:none;
 color:Black;
}
.ui-widget-content
{
    border-width:10px;
    border-color:Black;
    }
.ui-widget-overlay
{
background-color: #4b4b4b; 
}
.ui-dialog-titlebar-close 
{
    background-color:Black;
}
.ui-dialog-title
{
    display:none;
}
.ui-dialog .ui-dialog-titlebar
{
    display:none;
    }
</style>
    <script type="text/javascript">
        var customerCount = @(ViewBag.CustomerCount);
        function EditAccountPopup() {
            $('#dialog').dialog(
                { modal: true,
                    width: 450,
                    resizable: false,
                    closeText: "X" });
        }
    </script>
    <span class="name">Welcome, @AppSession.CurrentSession.Fullname |
        @*@Html.ActionLink("Edit Account", "Edit", "Account") |*@ <a id="lnkEdit" onclick="EditAccountPopup()"
            href="#">Edit Account</a> |
        @Html.ActionLink("Log out", "LogOut", "Session")
        @{
            
            if (ViewBag.CustomerCount != null && ViewBag.CustomerCount > 1)
            {
                <text>| </text> <a href="#" id="lnkchangeCustomer" class="lnkchangeCustomer">Change Customer</a>
            }
        }
      @*@Html.ActionLink("Edit Account", "Edit", "Account", new { @style = "color:#1E90FF; text-decoration:none" })  |
           @Html.ActionLink("Log out", "LogOut", "Session", new { @style = "color:#1E90FF; text-decoration:none" })*@
    </span>
    <div class="actions" style="padding-top:15px;">
        @*<span class="customername">Logged in as @AppSession.CurrentSession.CustomerName</span>*@
        @* <span class="customername">Customer:<div id="btnCustomername">@AppSession.CurrentSession.CustomerName</div></span>*@
        <table>
            <tr>
                <td style="font-size: 15px; font-weight: bold; color: #DCDCDC; padding-bottom: 10px;">
                    Customer:
                </td>
                <td>
                    <div id="btnCustomername" style="text-align: center;">
                        @if (@AppSession.CurrentSession.IsAgent)
                        {


                            if (!string.IsNullOrWhiteSpace(AppSession.CurrentSession.CustomerName))
                            {
                              <a href="#" id="lnkchangeCustomer" class="lnkchangeCustomer">@AppSession.CurrentSession.CustomerName</a>  
                            
                            }
                            else
                            {
                                <a href="#" id="lnkchangeCustomer" class="lnkchangeCustomer">Select Customer</a>  
                           
                            }
                            //this used in order_history_search.js for Ticket #78
                        <a href='@Url.Action("RenderCustomerList", "Customer")' id="aChangeCustomerUrl" style="display:none" >Change CustomerUrl</a>
                        }
                        else
                        {
                            @AppSession.CurrentSession.CustomerName
                        }</div>
                </td>
            </tr>
        </table>
    </div>
</div>
<div id="dialog" title="Change your Password"  style="display: none; overflow: visible;">
    @using (Html.BeginForm("Edit", "Account", FormMethod.Post, new { id = "account_form", @class = "form" }))
    {	<table><tr><td style="font-weight:bold;font-size:18px;padding-top:10px;">Change your Password</td>
               <td style="font-weight:900;font-size:15px;text-align:right;"><a href="#" onclick="$('#dialog').dialog('close');"  style="text-decoration:none;"><img src="@Url.Content("~/Content/images/framework/pop_close.png")" style="width:15px;height:15px;" alt="close" /></a></td></tr></table>
        
        <p style="padding-top:20px;">
          @*  <label for="Email_address">
                Email address</label><br />*@
              <b>  Email address</b><br /><br />
            <span>
           
                @if (AppSession.CurrentSession != null && AppSession.CurrentSession.Current != null && AppSession.CurrentSession.Current.Id != null)
                {
                         
                    <label for="email" style="font-weight:bold;color:Gray;"><i> @Ap21API.Entities.Person.Person.Find(id: @AppSession.CurrentSession.Current.Id).Contacts.Email</i></label>}
                else
                {
                    <label for="email">
                        &nbsp;</label>
                }</span>
        </p>
        <p>
            <label for="Password">
                Password</label><br />
            <span>
                <input id="password" name="password" type="password" class="textbox" style="width: 400px;"/></span>
        </p>
        <p>
            @*<label for="Confirm_password"></label>*@
               <b> Confirm password</b><br />
            <span>
                <input id="password_confirmation" name="password_confirmation" type="password" class="textbox" style="width: 400px;" /></span>
        </p>
        
            <table>
                <tr>
                    <td align="left">
                        <input type="submit" class="btn btn-info" name="commit"  value="Save" />
                    </td>
                    <td align="right">
                        <a href="#" onclick="$('#dialog').dialog('close');"  style="text-decoration:none; padding-left:298px;font-weight:bold;color:Gray;">Cancel</a>
                    </td>
                </tr>
            </table>
        
    }
</div>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/_EmptyHeader.cshtml
<div id="header">
   
    <div class="logo">
        <img src="@Url.Content("~/Content/images/framework/logo.png")" alt="SalesNet.Logo" /></a>
	</div>

    <div class="search">&nbsp;</div> 

    <div class="account_details">
	    <span class="name">Welcome, @AppSession.CurrentSession.Fullname</span>
	    <div class="actions">
		    <ul class="layout">
			    <li>@Html.ActionLink("Log out", "LogOut", "Session")</li>
		    </ul>
	    </div>
    </div>

</div>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/_Footer.cshtml
<div id="footer" style="padding:20px;">
	<span class="copyright">SalesNet @Html.GetSalesNetVersion() - Copyright © @DateTime.Now.Year Apparel<sup>21</sup></span>
</div>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/_Header.cshtml
<div id="header">
   
    <div class="logo" style="padding:15px;">
        <a><img src="@Url.Content("~/Content/images/framework/trans-logo.png")" alt="SalesNet.Logo" /></a>
	</div>

	<div class="search">&nbsp;</div> 

	@if (ViewData["HideAccountDetails"] == null)
    {
        @*@Html.Partial("_AccountDetails")*@
        Html.RenderAction("RenderAccountDetails", "Account");
    }
</div>

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/_HtmlHead.cshtml
<meta http-equiv="X-UA-Compatible" content="IE=9,8" />
<title>SalesNet</title>

<link href="@Url.Content("~/Content/favicon.ico")" rel="icon" />

<link href="@Url.Content("~/Content/javascripts/extjs/resources/css/ext-all.css")" rel="stylesheet" type="text/css" media="screen" />
<link href="@Url.Content("~/Content/stylesheets/main.css")" rel="stylesheet" type="text/css" media="screen"/>
<link href="@Url.Content("~/Content/stylesheets/print.css")" rel="stylesheet" type="text/css" media="print"/>
<link href="@Url.Content("~/Content/stylesheets/newdesignstyle.css")" rel="stylesheet" type="text/css" />
<link href="@Url.Content("~/Content/javascripts/extjs/resources/css/ext-ie.css")" rel="stylesheet" type="text/css" media="screen" />

<script type="text/javascript" >
    host = "@Url.Content("~")";
</script>

@if (!HttpContext.Current.IsDebuggingEnabled)
{
    <script src="@Url.Content("~/Content/javascripts/extjs/ext-all-debug.js")" type="text/javascript" ></script>
     <script src="@Url.Content("~/Content/javascripts/SalesNet/json2.js")" type="text/javascript" ></script>
        
    <script type="text/javascript" >
        Ext.Loader.setConfig({
            enabled: true,
            paths: {
                'Ext': host + 'Content/javascripts/extjs/src' /*'Content/javascripts/extjs/src'*/
            }
        });
    </script>
	@Html.Partial("_JavaScript.Debug")
}
else
{
	<script src="@Url.Content("~/Content/javascripts/extjs/ext-all-debug.js")" type="text/javascript" ></script>
	<script src="@Url.Content("~/Content/javascripts/salesnet.min.js")" type="text/javascript"></script>
     <script src="@Url.Content("~/Content/javascripts/SalesNet/json2.js")" type="text/javascript" ></script>
}

@Html.ShowFlash()

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Shared/_Sidebar.cshtml
@Html.JavaScript("SalesNet.Navigation.init();")
<div id='sidebar'>
	
</div>