SalesNet v1.3/trunk/SalesNet.WebUI/Models/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SalesNet.WebUI.Models
{
    public class ProductViewModel
    {
        public string Name { get; set; }
        public string Category { get; set; }
    }
}

SalesNet v1.3/trunk/SalesNet.WebUI/Controllers/OrderController.cs
using System;
using System.Web.Mvc;
using Ap21API.Entities.Customer;
using Ap21API.Entities.Order;
using SalesNet.Domain.Entities;
using SalesNet.WebUI.DataSetGenerators;
using SalesNet.WebUI.Infrastructure;
using SalesNet.WebUI.Models;
using SalesNet.WebUI.Helpers;
using SalesNet.WebUI.Classes;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using Order = Ap21API.Entities.Order.Order;


namespace SalesNet.WebUI.Controllers
{  
    [NoCache]
    [EnhancedAuthorizedAttribute]
    public partial class OrderController : BaseController
    {
        private CustomerCreditStatus creditStatus;
        private readonly IAppSessionWrapper session;

        public OrderController(IAppSessionWrapper appSessionWrapper)
        {
            session = appSessionWrapper;
        }

        

        public ViewResult Index()
        {
            ViewBag.CustomerId = session.Current.CustomerId;
            TempData["ActivePage"] = "Order History";
            

            return View();
        }

        [ValidateInput(false)]
        public PartialViewResult HistoryIndex(string trans_num = null, string ref_num = null, string created_date_from = null,
            string created_date_to = null, string product_code_desc = null, string order_type = null)
        {
            var searchCriteria = new OrderSearchViewModel(trans_num, ref_num, created_date_from,
            created_date_to, product_code_desc, order_type);
            return PartialView(searchCriteria);
        }

        [ValidateInput(false)]
        public PartialViewResult HistoryItem(string trans_num = null, string ref_num = null, string created_date_from = null,
            string created_date_to = null, string product_code_desc = null, string order_type = "Orders", int page = 1)
        {
            
            const int pageRow = 20;
            int startRow = (page - 1) * pageRow + 1;	

            try
            {
                ValidateSearchCriteria(ref trans_num, ref ref_num, ref created_date_from, ref created_date_to, ref product_code_desc, ref order_type);
            }
            catch (System.FormatException)
            {
                return PartialView();
            }

            var searchCriteria = new OrderSearchViewModel(trans_num, ref_num, created_date_from, 
                created_date_to,product_code_desc, order_type);

            var orderRepository = Orders.Find(createdDateFrom: created_date_from, createdDateTo: created_date_to, customerReference: ref_num, pageRows: pageRow,
                                                 productFilter: product_code_desc, startRow: startRow,
                                                 transactionNumber: trans_num, transactionType: order_type);


            if (orderRepository!=null && orderRepository.Order.Count>0)
            {
                int PageCurrent = (int)Math.Ceiling((decimal)orderRepository.PageStartRow / pageRow);
                var viewModel = orderRepository.Order.ToPagedList(PageCurrent - 1, pageRow,
                                                                  orderRepository.TotalRows, searchCriteria.ToDictionary());
                return PartialView(viewModel); 
            }
            else
            {
                return PartialView();
            }
        }

        private void ValidateSearchCriteria(ref string trans_num, ref string ref_num, ref string created_date_from,
            ref string created_date_to, ref string product_code_desc, ref string order_type)
        {            
            if (trans_num == "" || trans_num == "Trans.#")
            {
                trans_num = null;
            }

            if (ref_num == "" || ref_num == "Ref #")
            {
                ref_num = null;
            }

            if (created_date_from == "" || created_date_from == "Created From")
            {
                created_date_from = null;
            }

            if (created_date_to == "" || created_date_to == "Created To")
            {
                created_date_to = null;
            }

            if (product_code_desc == "" || product_code_desc == "Product Code/Desc")
            {
                product_code_desc = null;
            }

            if (order_type == "")
            {
                order_type = null;
            }

            if (trans_num != null)
            {
                Regex regex = new Regex(@"^[0-9]+$");
                bool b = regex.IsMatch(trans_num);
                if (!b)
                    throw new System.FormatException();
            }

            if (created_date_from != null)
            {
                created_date_from = String.Format("{0:yyyy-MM-dd}", Convert.ToDateTime(created_date_from));
            }

            if (created_date_to != null)
            {
                created_date_to = String.Format("{0:yyyy-MM-dd}", Convert.ToDateTime(created_date_to));
            }
        }

        public PartialViewResult CurrentOrders()
        {
			PutCurrentOrderInViewBag();
			return PartialView();
        }

        [HttpPost]
        public ActionResult CurrentOrders(CurrentOrderViewModel model)
        {
            return RedirectToAction("Index", "Home");
        }

		public PartialViewResult CurrentOrdersDetail()
		{
			PutCurrentOrderInViewBag();
			return PartialView();
		}

        [HttpGet]
        public ActionResult DeleteOrders()
        {
            try
            {
                Domain.Entities.Order.DeleteCurrentOrder();
            }
            catch (Exception e)
            {
                FlashError(e.Message);
            }

			PutCurrentOrderInViewBag();
            return PartialView("CurrentOrders");
        }

        [HttpGet]
        public void DeleteOrdersFromFinalisePage()
        {
            try
            {
                Domain.Entities.Order.DeleteCurrentOrder();
            }
            catch (Exception e)
            {
                FlashError(e.Message);
            }
        }

        [HttpGet]
        public ActionResult RemoveOrder(string orderDetailId)
        {
            var model = new MessageModel();

            try
            {
                Domain.Entities.Order.DeleteCurrentSingleOrder(orderDetailId);
                model.MessageCode = 3;
            }
            catch (Exception e)
            {
                model.Error = e.Message;
            }

			PutCurrentOrderInViewBag();
            return PartialView("CurrentOrders", model);
        }

        [HttpGet]
        public void RemoveOrderFromFinalisePage(string orderDetailId)
        {
            var model = new FinaliseOrderViewModel();

            try
            {
                Domain.Entities.Order.DeleteCurrentSingleOrder(orderDetailId);
                model.MessageModel.MessageCode = 3;
            }
            catch (Exception e)
            {
                model.MessageModel.Error = e.Message;
            }
        }


        private void AlertCreditStatus()
        {
            // used to disable/enable the submit link
            TempData["EnableSubmit"] = creditStatus.CanContinue;

            if(creditStatus.CanContinue)
            {
                FlashWarning(description: creditStatus.Message()); 
            }else
            {
                FlashError(description: creditStatus.Message());
            }    
        }

        [ValidateInput(false)]
        public ActionResult savedelivery(string id, string customerReference, string deliveryInstructions, string specialInstructions)
        {
            try
            {

                Domain.Entities.Order.SaveDeliveryDetails(customerReference, deliveryInstructions, specialInstructions);
                
              //FlashNotice("Delivery Details Saved successfully");                
                //return RedirectToAction("FinaliseOrder");
              return RedirectToAction("Index", "Product");
            }
            catch (Exception e)
            {
                FlashError(e.Message);

                return RedirectToAction("FinaliseOrder");
            }
        }
        
        [ValidateInput(false)]
        
        public ActionResult SendOrder(string id, string customerReference, string deliveryInstructions, string specialInstructions)
        {
            try
            {
                Domain.Entities.Order.FinaliseCurrentOrder(customerReference, deliveryInstructions, specialInstructions);
                
                FlashNotice("Order has been sent to process successfully");

                return RedirectToAction("OrderDetails", new { id = id });
               
            }
            catch (Exception e)
            {
                FlashError(e.Message);

                return RedirectToAction("FinaliseOrder");
            }         
        }
        

        [HttpPut]
        public void ChangeDeliveryAddress(string id)
        {
            Domain.Entities.Order.ChangeDeliveryAddress(id);
        }

        [HttpGet]
        public ActionResult ChangeDeliveryAddress1(string id)
        {
            Domain.Entities.Order.ChangeDeliveryAddress(id);
            return RedirectToAction("FinaliseOrder");
        }
        [HttpGet]
        public ActionResult FinaliseOrder()
        {
            var model = Domain.Entities.Order.CurrentOrder ?? new Order();
            var customer = Customer.Find(AppSession.CurrentSession.CustomerId);
            creditStatus = new CustomerCreditStatus(customer);
            if (customer != null)
            {
                ViewBag.Locations = customer.Locations.Location;
            }
            if(!creditStatus.IsNormal)
            {
                AlertCreditStatus();
            }
            TempData["ActivePage"] = "ViewCart";
            return View(model); 
        }

        public PartialViewResult FinaliseOrderDetail()
        {
            TempData["customerReference"] = TempData["customerReference"] ?? String.Empty;

SalesNet v1.3/trunk/SalesNet.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Web;
using System.Web.Caching;
using System.Web.Configuration;
using System.Web.Mvc;
using Ap21API.Entities.Product;
using Ap21API.Entities.Reference;
using SalesNet.WebUI.DataSetGenerators;
using SalesNet.WebUI.Helpers;
using SalesNet.WebUI.Infrastructure;
using SalesNet.WebUI.Models;
using SalesNet.WebUI.Classes;

namespace SalesNet.WebUI.Controllers
{
    [EnhancedAuthorized]
    [NoCache]
    public class ProductController : BaseController
    {
        private int defaultPageSize = Convert.ToInt16(ConfigurationManager.AppSettings["ProductsPageSize"]);
        private const int pagesToSkip = 1;
        private string searchQuery = String.Empty;       

        public ActionResult Index()
        {
            TempData["ActivePage"] = "Product";
            return View();
        }
       
        private ReferenceTree GetReferenceTree()
        {
            string currentCustomerId = AppSession.CurrentSession.Current.CustomerId;
            string previousCustomerId = (String)HttpRuntime.Cache.Get("customerId");
            ReferenceTree referenceTree = null;

            // check the cached customer id
            if (!String.IsNullOrEmpty(previousCustomerId) &&
                (String.Compare(currentCustomerId, previousCustomerId, true) == 0))
                referenceTree = (ReferenceTree)HttpRuntime.Cache.Get("styleReferenceTree");

            if (!String.IsNullOrEmpty(currentCustomerId) && 
                !(String.Compare(currentCustomerId, previousCustomerId, true) == 0))
                HttpRuntime.Cache.Insert("customerId", currentCustomerId);

            // retrieve the style levels
            if(referenceTree == null)
            {
                var styleLevel1 = ConfigurationManager.AppSettings["style_levels_1"];
                var styleLevel2 = ConfigurationManager.AppSettings["style_levels_2"];
                var styleLevel3 = ConfigurationManager.AppSettings["style_levels_3"];

                referenceTree = ReferenceTree.Find(styleLevel1, styleLevel2, styleLevel3);
                
                HttpRuntime.Cache.Insert("styleReferenceTree", referenceTree);
            }
            
            return referenceTree;
        }


        [HttpGet]
        public PartialViewResult Search()
        {
            var productSearchViewModel = new ProductCategoryViewModel(GetReferenceTree());

            var styleLevel1 = ConfigurationManager.AppSettings["style_levels_1"];
            var styleLevel2 = ConfigurationManager.AppSettings["style_levels_2"];
            var styleLevel3 = ConfigurationManager.AppSettings["style_levels_3"];

            // styleLevels are class variables
            ViewData["firstStyleLevelName"] = ReferenceType.Find(styleLevel1).Name; 
            if (!String.IsNullOrEmpty(styleLevel2))
            {
                 ViewData["secondStyleLevelName"] = ReferenceType.Find(styleLevel2).Name; 
                if (!String.IsNullOrEmpty(styleLevel3))
                {
                    ViewData["thirdStyleLevelName"] = "All";//Modified by Raju ReferenceType.Find(styleLevel3).Name;
                }
            }
            

            return PartialView(productSearchViewModel);
        }

        [ValidateInput(false)]
        public PartialViewResult ProductList(string product_desc, string category_season, string category_type, string category_product, int? page,string category_name)
        {
            if (product_desc == "" || product_desc == "Code/Description")
            {
                product_desc = null;
            }
            if (category_name!=null)
            {
                ViewData["category_name"] = category_name;
            }

            int currentPageIndex = page.HasValue ? page.Value - pagesToSkip : 0;
            Dictionary<string, string> searchCriteria = GenerateSearchCriteria(product_desc, category_season, category_type, category_product);
            searchQuery = FormatSearchQuery(searchQuery);

            bool showNoStockProducts = bool.Parse(WebConfigurationManager.AppSettings["ShowNoStockProducts"]);

            var products = ProductsSimple.Find(query: searchQuery, styleQuery: product_desc, orderBy: "{Code:asc}", startRow: defaultPageSize * currentPageIndex + 1, pageRows: defaultPageSize, showNoStockProducts: showNoStockProducts);
            var productsAll = products.ProductSimple.ToPagedList(currentPageIndex, defaultPageSize, products.TotalRows, searchCriteria);

            return PartialView(productsAll);
        }
        

        private Dictionary<string, string> GenerateSearchCriteria(string productDescription, string categorySeason, string categoryType, string categoryProduct)
        {
            Dictionary<string, string> searchCriteria = new Dictionary<string, string>();

            if (!string.IsNullOrEmpty(productDescription))
            {
                searchQuery += productDescription + ":";
                searchCriteria.Add("product_desc", productDescription);
            }

            if (!string.IsNullOrEmpty(categorySeason))
            {
                searchQuery += categorySeason + ":";
                searchCriteria.Add("category_season", categorySeason);
            }

            if (!string.IsNullOrEmpty(categoryType))
            {
                searchQuery += categoryType + ":";
                searchCriteria.Add("category_type", categoryType);
            }

            if (!string.IsNullOrEmpty(categoryProduct))
            {
                searchQuery += categoryProduct + ":";
                searchCriteria.Add("category_product", categoryProduct);
            }

            return searchCriteria;
        }

        private static string FormatSearchQuery(string searchQuery)
        {
            return searchQuery.Length > 0 ? searchQuery.Substring(0, searchQuery.Length - 1) : searchQuery;
        }

        public PartialViewResult ProductMenu()
        {
            var productCategoryViewModel = new ProductCategoryViewModel(GetReferenceTree());
            
            return PartialView(productCategoryViewModel);
        }

        [HandleError]
        [OutputCache(Duration = 300, VaryByParam = "id")]
        public PartialViewResult OrderDetail(string id, string isFromFinalizeOrder)
        {
            OrderDetailProductModel product = new OrderDetailProductModel(id, isFromFinalizeOrder);
            ViewBag.Note =  ProductNoteTypeHelper.GetNote(product.Product.Code);

            HttpRuntime.Cache.Insert("productId", id, null, DateTime.Now.AddMinutes(5.0), Cache.NoSlidingExpiration);
            HttpRuntime.Cache.Insert("product", product, null, DateTime.Now.AddMinutes(5.0), Cache.NoSlidingExpiration);
            
            return PartialView("OrderDetail", product);
        }

        [HandleError]
        public ActionResult Skus(string id)
        {
            if (id.Contains(".json")) id = id.Replace(".json", "");
            var product = (OrderDetailProductModel) HttpRuntime.Cache.Get("product");
            var productId = (String)HttpRuntime.Cache.Get("productId");

            if(id.Equals(productId) && product != null)
            {
                return ProductEntryGridDataSet.Arrange(product);
            }else
            {
                product = new OrderDetailProductModel(id, "false");
                return ProductEntryGridDataSet.Arrange(product);
            }
        }
    }
}

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Product/Index.cshtml
@{
    ViewBag.Title = "ProductIndex";
    Layout = "~/Views/Shared/ProductLayout.cshtml";
}

@{ Html.RenderAction("Search", "Product");}

@{ Html.RenderAction("ProductList", "Product");}

@section Sidebar
{
      @{ Html.RenderAction("ProductMenu", "Product");}
}

@section Order_Sidebar
{
    <div id="CurrentOrder" style ="display:none;">
     @* @{ Html.RenderAction("CurrentOrders", "Order");}*@
    </div>
}

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Product/OrderDetail.cshtml
@model SalesNet.WebUI.Models.OrderDetailProductModel           
@{
    int lowStockThreshold = 180;
    int.TryParse(System.Configuration.ConfigurationManager.AppSettings["LowStockThreshold"], out lowStockThreshold);
    int highStockThreshold = 0;
    int.TryParse(System.Configuration.ConfigurationManager.AppSettings["HighStockThreshold"], out highStockThreshold);
}
<script type="text/javascript">
    var showIncomingStock = '@System.Configuration.ConfigurationManager.AppSettings["ShowIncomingStock"]';
    showIncomingStock = showIncomingStock.toLowerCase();

    function resolveHref(ancr) {
        var vHostName = document.location.href;
        vHostName = vHostName.replace("Products","");
        var aCLink = ancr;
        aCLink.href = aCLink.href.replace(vHostName, 'http://');
        aCLink.target = "blank";
    }
    function scrollLeft() {
        //var divRight = $('#product-order-entry-grid');
        //var divLeft = $('#product-order-list');
        var divRight = document.getElementById('product-order-entry-grid');
        var divLeft = document.getElementById('product-order-list');
        divRight.scrollTop = divLeft.scrollTop;
        //divRight.scrollTop(divLeft.scrollTop());
    }

    function scrollRight() {
        //var divRight = $('#product-order-entry-grid table');
        //var divLeft = $('#product-order-list table');
        var divRight = document.getElementById('rightTbl');
        var divLeft = document.getElementById('leftTbl');
        var scroller = document.getElementById('scroller');
        divLeft.scrollTop=scroller.scrollTop;
        divRight.scrollTop=scroller.scrollTop;
        //divLeft.scrollTop(divRight.scrollTop());
    }

    $(document).ready(function () {
        // alert("testing");
        // $(".product_qty .x-grid-table").css({ 'margin-bottom': '0px' });
        //debugger;
        // alert($(".x-grid-table x-grid-table-resizer").class);
        //$(".x-grid-table x-grid-table-resizer").css({ 'margin-bottom': '0px' });
      //  document.write("<style type='text/css'>.product_qty .x-grid-table{margin-bottom: 0px;}</style>");
    });       
</script>
@using (Html.BeginForm("AddToOrder", "Order", new { productId = Model.Product.Id, isFromFinalizeOrder = Model.IsFromFinalizeOrder ?? "" }, FormMethod.Post, new { id = "product_qty_form", title = "Product Order" }))
{

    <style type="text/css">
    td.x-grid-cell div.x-grid-cell-inner
    {
          height:35px;
    }
    #product-order-list .x-grid-cell-first div.x-grid-cell-inner{width:96px;}
    form p > span {
display: inline;
width: auto;
}
form span ul 
{
    margin-left:20px;
    }
    form span ol 
{
    margin-left:20px;
    }
    .markdown_price{display:none;}
   .x-grid-table{margin-bottom:0px;}
   .x-grid-header-row{display:none;}
   .x-grid-cell-inner{width:55px;}
    #leftTbl{padding-left:15px;max-height:190px;}
    .x-panel-body-default,.x-panel .x-grid-body {border-width:0px;}
    #rightTbl{max-height:190px;}  
    </style>
  
    <div class="product_qty">
        <div class="header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                ×</button>
            <h1>
                Order Product</h1>
        </div>
        <div class="image" style="text-align: center; width: 150px; height: 150px; overflow: visible;">
            @Html.GetProductImage(Model.Product.Code)
        </div>
        <div class="details" style="margin-left: 5px;">
            <div class="product_info">
                <h1 class="code">@Model.Product.Code.ToUpper()</h1>
                <h1 class="name">@Model.Product.Name</h1>
                @{
    var varProductNoteType = Ap21API.Entities.Product.ProductNoteTypes.Find(Model.Product.Id);
                }
                @if (varProductNoteType != null && varProductNoteType.ProductNoteType.Count > 0)
                {
                    for (int intLoop = 0; intLoop < varProductNoteType.ProductNoteType.Count; intLoop++)
                    {
                        if (System.Configuration.ConfigurationManager.AppSettings["ProductNoteType"] != null && System.Configuration.ConfigurationManager.AppSettings["ProductNoteType"] == varProductNoteType.ProductNoteType[intLoop].Code)
                        {
                                <div  id="divPageContent" style="font-style: italic;"  >
                               
                                @{
                            String strContent =varProductNoteType.ProductNoteType[intLoop].Note;
                            strContent = strContent.Replace("href", "onclick='resolveHref(this);' href");
                                }
                                   @MvcHtmlString.Create(strContent)
                                   
                                  @* <iframe id="iframe" frameborder="0" src="data:text/html;charset=utf-8,@varProductNoteType.ProductNoteType[intLoop].Note" style="width: 100%; height: 200px;"></iframe>*@
                                
                                </div>
                            break;
                        }
                    }
                }
                
                <div id="discount-msg" style="line-height: 25px;">
                </div> 

                <div class="pricing" style="line-height: 25px; padding-top: 3px; ">
                    <ul>
                        <li><span class="detail_item from actualprice">
                            @if (Html.IsPriceDifferentBySku(Model))
                            {
                                <strong>From </strong>
                            }
                            @if (AppSession.CurrentSession.CurrentOrderCurrencyFormat != null)
                            {
                              @Html.FormatCurrency(Model.ProductPriceFrom, AppSession.CurrentSession.CurrentOrderCurrencyFormat)
                            }
                            else
                            {
                                @Html.FormatCurrency(Model.ProductPriceFrom, Model.OrderDetailProduct.Currency.Format)
                            }
                        </span></li>
                        @if (Model.Discount > 0)
                        {
                            <li style="padding-bottom: 3px; "><span class="detail_item discount">Your Discount <strong>
                             @if (AppSession.CurrentSession.CurrentOrderCurrencyFormat != null)
                             {
                                @Html.FormatCurrency(Model.Discount, AppSession.CurrentSession.CurrentOrderCurrencyFormat)
                             }
                             else
                             {
                                @Html.FormatCurrency(Model.Discount, Model.OrderDetailProduct.Currency.Format)
                             }
                            </strong></span></li>
                        }
                       @* @if (Html.IsPriceDifferentBySku(Model))
                        {<li><span class="detail_item from"><strong>From </strong>
                         @if (AppSession.CurrentSession.CurrentOrderCurrencyFormat != null)
                         {
                            @Html.FormatCurrency(Model.ProductPriceFrom, AppSession.CurrentSession.CurrentOrderCurrencyFormat)
                         }
                         else
                         { 
                            @Html.FormatCurrency(Model.ProductPriceFrom, Model.OrderDetailProduct.Currency.Format)
                         }
                    </span></li>
                        }*@
                        <li style="color:#6F6F6F;"><span class="detail_item from rrp">
                            @{
                        string From = "";
                        if (Html.IsRRPPriceDifferentBySku(Model))
                        {
                            From = "From";
                        }      
                            }
                            <span>
                            @{
                                string emptySpace = " ";
                                  if (AppSession.CurrentSession.CurrentOrderCurrencyFormat != null)
                                  {
                                    @Model.RrpText @emptySpace @From @emptySpace @Html.FormatCurrency(Model.RRPPriceFrom, AppSession.CurrentSession.CurrentOrderCurrencyFormat)
                                  }
                                  else
                                  {
                                    @Model.RrpText @emptySpace @From @emptySpace @Html.FormatCurrency(Model.RRPPriceFrom, Model.OrderDetailProduct.Currency.Format)
                                  }
                            }
                          </span>
                        </span>&nbsp </li>
                    </ul>
                </div>
                <b>
                    <h4 id="low-stock-message" class="hidden">
                        <label class="error">
                        </label>
                    </h4>
                </b>
            </div>
            <div class="product_spec">
                <div id="unit_cost" class="hidden" style="background-color:#D1F0FF;">
                    <h1 style="display:none;">
                        Selected Product</h1>
                    <ul id="unit_cost_list">
                    </ul>
                </div>
            </div>
        </div>
        <div class="table-input" style="padding:10px;">
            @Html.Partial("ProductStockAvailabilityLegend")
            @Html.Hidden("low-stock-threshold", lowStockThreshold)
            @Html.Hidden("high-stock-threshold", highStockThreshold)
            @*<div style="overflow: auto; height: 230px; width: 800px;">*@
            <div style="position:relative">
                <div id="grid_table">
                    <div id="product-order-list" style="overflow-y: hidden; overflow-x: hidden;height:auto;width:auto;" >
                   @* <div id="product-order-list">*@
                    </div>
                    <div class="detail_item_total">
                        <div class="detail_item_total-wrapper" style="padding-left: 15px;padding-top:25px;">
                            <strong>Total Quantity </strong><span id="totalquantity"></span>
                        </div>
                    </div>
                </div>
                <div id="product-order-entry-grid" style="overflow-y: hidden; height: auto; width: auto; overflow-x: auto; max-height: 240px;max-width:600px;"  >
                    <div id="product-order-details">
                    </div>
                </div>
                <div id="scroller" class="x-component x-scroller x-scroller-vertical x-component-default  x-component-docked-right x-component-default-docked-right x-docked-noborder-right x-docked-noborder-bottom"
                     style="width: 18px; height: 215px;float:left;overflow-y: auto;" role="presentation"  onscroll='scrollRight();'>
                    <div class="x-stretcher" id="ext-gen1074" style="width: 1px; height: 628px;"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="buttons" id="product-order-entry-form-butons">
        @if (Model.IsExistingOrderDetail)
        {
@*    <input name="commit" type="submit" value="Update" class="btn btn-info" id="addToOrder"/> *@
            <button name="commit" type="submit" value="Update" class="btn btn-info btn-large btn-add"
                    id="addToOrder">
                Add</button>
           
        }
        else
        {
@* <input name="commit" type="submit" value="Add" class="btn btn-info" id="addToOrder"/> *@
            <button name="commit" type="submit" value="Add" class="btn btn-info btn-large btn-add"
                    id="addToOrder">
                Add</button>
        }
        <a href="#" id="cancelAddToOrder" class="">Cancel</a>
    </div>
    
    
}

SalesNet v1.3/trunk/SalesNet.WebUI/Views/Product/ProductStockAvailabilityLegend.cshtml
<div class="legend">
    <span>
        <i class="symbol stock_low"></i><label>Low Stock</label>
        </span>
	<span>
    <i class="symbol stock_unavailable"></i><label>Out of Stock</label>
    </span>
    @{
        string showIncomingStock=System.Configuration.ConfigurationManager.AppSettings["ShowIncomingStock"];
        showIncomingStock = showIncomingStock.ToLower();
    }
    @if (showIncomingStock != null && showIncomingStock != "" && showIncomingStock == "true")
    {
        <span><i class="symbol stock_incoming"></i><label>Incoming Stock</label></span>
    }
</div>